api_platform:
    version: 0.2.0
    title: "RESTful Translator"
    description: "API documentation"
    enable_swagger: true
    enable_swagger_ui: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        order: 'ASC'
        order_parameter_name: 'sort'
        pagination:
            page_parameter_name: page
            client_items_per_page: true
            items_per_page: 50
            items_per_page_parameter_name: 'size'
