api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        order: 'ASC'
        order_parameter_name: 'sort'
        pagination:
            page_parameter_name: page
            client_items_per_page: true
            items_per_page: 50
            items_per_page_parameter_name: 'size'
    # Enable the Swagger documentation and export.
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true
