services:
  search_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      tags: [ 'api_platform.filter' ]
  order_filter:
      parent: 'api_platform.doctrine.orm.order_filter'
      tags: [ 'api_platform.filter' ]
