services:
  translation.search_filters:
      parent: 'api_platform.doctrine.orm.search_filter'
      tags: [ 'api_platform.filter' ]
  translation.order_filter:
      parent: 'api_platform.doctrine.orm.order_filter'
      tags: [ 'api_platform.filter' ]
